### ISSUE TITLE
Setup the django project

### ISSUE THREAD

**Issue by Geekfish** [CodeHubOrg/bookxchange#1]
Just a server that runs!

**Comment by katjad** [comment]
Done - thanks for help with the venv

**Comment by Geekfish** [comment]
nice one @katjad !
Should we keep this one open until the project structure / requirements.txt etc are into the repo?

**Comment by katjad** [comment]
Haha yes, we should. I just closed it because I did it on local wich is a bit beside the point :)

**Comment by Geekfish** [comment]
This should now be done.
