### ISSUE TITLE
Add basic user registration + login

### ISSUE THREAD

**Issue by Geekfish** [CodeHubOrg/bookxchange#2]

**Comment by Geekfish** [comment]
Might be a good idea to look into adding a custom authentication model straight from the start (or soon after):
https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#specifying-a-custom-user-model

**Comment by katjad** [comment]
oops I did not checkout the link as I did not look at the issue anymore, have followed an MDN tutorial so far, but will look into custom model. One thing not good at  the moment is that you need username instead of email to log on - but that's probably not the reason to go with a custom model?
