### ISSUE TITLE
User can administer books

### ISSUE THREAD

**Issue by Geekfish** [CodeHubOrg/bookxchange#4]
- Expected Fields:
    - Title
    - Author
    - ISBN?
    - Automatically filled: book owner
    - NICE TO HAVE: Cover 
    - **VERY NICE TO HAVE: fetch from goodreads** => this now the only left; a bit on the back burner for now, so far fetching from openlibrary
- Add/Update/Delete View (single book)
- List MY books View (collection)

This can serve as a "parent" ticket, let's break down the tasks into smaller bits.

**Comment by katjad** [comment]
Maybe I best comment here, as I have done some of this but have not totally fulfilled any of the sub tasks. so I'll just write about my progress here. 

I have created a view with a form that adds a book, including uploading a cover img that goes into media/ at root level. Another view that shows a list of book. it was really tricky to sort out having static files served properly on the dev server, but hopefully that's sorted now.
