### ISSUE TITLE
Setup of dev environment

### ISSUE THREAD

**Issue by Geekfish** [CodeHubOrg/bookxchange#9]
Make the local development easy for a newcomer to setup.
This could be done with Vagrant or docker-compose or some other way. It could also be non-automated to start with (just some docs that people can follow)

**Comment by Geekfish** [comment]
After discussing, let's offer 2 sets of setups/instructions:

1. using a virtualenv locally
2. using docker

See dojocracy src for docker-compose example (and/or explore other options)

**Comment by Geekfish** [comment]
For the dockerization, it may be helpful to start just with dockerizing the database?

**Comment by katjad** [comment]
Can we close this?
